image: "ghcr.io/jethome-homeassistant/{arch}-builder"
build_from:
  aarch64: "ghcr.io/jethome-homeassistant/aarch64-base:3.22"
  armv7: "ghcr.io/jethome-homeassistant/armv7-base:3.22"
  armhf: "ghcr.io/jethome-homeassistant/armhf-base:3.22"
  amd64: "ghcr.io/jethome-homeassistant/amd64-base:3.22"
  i386: "ghcr.io/jethome-homeassistant/i386-base:3.22"
cosign:
  base_identity: https://github.com/jethome-homeassistant/docker-base/.*
  identity: https://github.com/jethome-homeassistant/builder/.*
args:
  YQ_VERSION: "v4.13.2"
  COSIGN_VERSION: "2.5.3"
labels:
  io.hass.type: builder
  org.opencontainers.image.title: "Home Assistant Builder"
  org.opencontainers.image.description: "Container-based build system for Home Assistant"
  org.opencontainers.image.source: "https://github.com/jethome-homeassistant/builder"
  org.opencontainers.image.authors: "The Home Assistant Authors (JetHome version)"
  org.opencontainers.image.url: "https://www.home-assistant.io/"
  org.opencontainers.image.documentation: "https://developers.home-assistant.io/"
  org.opencontainers.image.licenses: "Apache License 2.0"
